### ISSUE TITLE
AWS sdk version issue

### ISSUE THREAD

**Issue by sheldon-sminq** [jdamick/dropwizard-metrics-cloudwatch#2]
I get the following error, from the gradel build aws sdk version is 1.9.18 but i am using 1.10.2

java.lang.NoSuchMethodError: com.amazonaws.AmazonWebServiceRequest.copyPrivateRequestParameters()Ljava/util/Map;

**Comment by jdamick** [comment]
this is due to cloudwatch jar mismatch to aws core..

**Comment by jdamick** [comment]
released 0.1.5 with the update to maven central, should show up shortly:  http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.damick%22%20AND%20a%3A%22dropwizard-metrics-cloudwatch%22
