### ISSUE TITLE
Yaml parse error on startup. Conflicting setter definitions for property "seed"

### ISSUE THREAD

**Issue by tfeak** [jdamick/dropwizard-metrics-cloudwatch#4]
I tried using this with the most recent DropWizard (0.9.1) library and AWS (1.10.36) libraries. I get the following error on startup.

Failed to parse configuration at: metrics.reporters; Conflicting setter definitions for property "seed": java.security.SecureRandom#setSeed(1 params) vs java.security.SecureRandom#setSeed(1 params) (through reference chain: com.redemptiongames.game.server.GameServerConfig["metrics"]->io.dropwizard.metrics.MetricsFactory["reporters"])

I did a LOT of digging and it came down to the ClientConfiguration object on the CloudWatchReporterFactory. It currently contains a SecureRandom on it that causes this problem. It appears that you want to allow configuration of the ClientConfiguration AWS object through YAML. But it doesn't handle the SecureRandom well. I'm not sure if it's due to the SecureRandom implementation in Java 1.7, or if it's a recent change to ClientConfiguration in the AWS libraries that exposed the SecureRandom.

Also not sure exactly how to fix this best. You may have to include a configuration wrapper class to expose settings on ClientConfiguration via YAML instead of just relying on Amazon to provide a Jackson friendly version.

EDIT: As a workaround, I've removed the setter/getter for ClientConfiguration in a local copy of your classes and the problem has gone away.

**Comment by jdamick** [comment]
thanks for the report, i'll dig into it

**Comment by jdamick** [comment]
i pushed 0.1.6 that should fix these issues..
